In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("/mnt/c/Users/mercg/Downloads/homeprices (1).csv")
df

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [5]:
dummies = pd.get_dummies(df['town'])

In [7]:
merged = pd.concat([df,dummies], axis = 'columns')
merged

               town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000             True        False         False
1   monroe township  3000  565000             True        False         False
2   monroe township  3200  610000             True        False         False
3   monroe township  3600  680000             True        False         False
4   monroe township  4000  725000             True        False         False
5      west windsor  2600  585000            False        False          True
6      west windsor  2800  615000            False        False          True
7      west windsor  3300  650000            False        False          True
8      west windsor  3600  710000            False        False          True
9       robinsville  2600  575000            False         True         False
10      robinsville  2900  600000            False         True         False
11      robinsville  3100  620000            False         True         False
12      robinsville  3600  695000            False         True         False

In [8]:
final = merged.drop(['town', 'west windsor'], axis = 'columns')
final

    area   price  monroe township  robinsville
0   2600  550000             True        False
1   3000  565000             True        False
2   3200  610000             True        False
3   3600  680000             True        False
4   4000  725000             True        False
5   2600  585000            False        False
6   2800  615000            False        False
7   3300  650000            False        False
8   3600  710000            False        False
9   2600  575000            False         True
10  2900  600000            False         True
11  3100  620000            False         True
12  3600  695000            False         True

In [9]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [11]:
X = final.drop('price', axis = 'columns')
Y = final['price']

In [12]:
model.fit(X, Y)

LinearRegression()

In [15]:
model.predict([[3400, 0, 0]])

/home/mercg/anaconda3/envs/py310/lib/python3.10/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([681241.66845839])

In [17]:
df

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [18]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [19]:
dfle = df
dfle.town = le.fit_transform(dfle.town)
dfle

    town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [23]:
x = df[['town','area']].values
y = dfle.price

In [30]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
x = ohe.fit_transform(x).toarray()
x

ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,).

In [31]:
d = {'sales': [100000,222000,1000000,522000,111111,222222,1111111,20000,75000,90000,1000000,10000], 'city': ['Tampa','Tampa','Orlando','Jacksonville','Miami','Jacksonville','Miami','Miami','Orlando','Orlando','Orlando','Orlando'], 'size': ['Small', 'Medium','Large','Large','Small','Medium','Large','Small','Medium','Medium','Medium','Small',]}

In [32]:
df = pd.DataFrame(data=d)
df.head()

     sales          city    size
0   100000         Tampa   Small
1   222000         Tampa  Medium
2  1000000       Orlando   Large
3   522000  Jacksonville   Large
4   111111         Miami   Small

In [33]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(handle_unknown = 'ignore', sparse_output= False).set_output(transform='pandas')

In [37]:
ohet = pd.get_dummies(df.city)

In [39]:
merged = pd.concat([df,ohet], axis = 1)

In [43]:
merged.drop(columns='city')

      sales    size  Jacksonville  Miami  Orlando  Tampa
0    100000   Small         False  False    False   True
1    222000  Medium         False  False    False   True
2   1000000   Large         False  False     True  False
3    522000   Large          True  False    False  False
4    111111   Small         False   True    False  False
5    222222  Medium          True  False    False  False
6   1111111   Large         False   True    False  False
7     20000   Small         False   True    False  False
8     75000  Medium         False  False     True  False
9     90000  Medium         False  False     True  False
10  1000000  Medium         False  False     True  False
11    10000   Small         False  False     True  False